from django.urls import path
from ArvyoApp import homeViews

# Remova a linha "from . import views"

urlpatterns = [

    # Home
    path('', homeViews.index, name='index'),
    path('add-bank', homeViews.addBank, name='addBank'),
    path('add-card', homeViews.addCard, name='addCard'),
    path('add-new-account', homeViews.addNewAccount, name='addNewAccount'),
    path('affiliates', homeViews.affiliates, name='affiliates'),
    path('analytics', homeViews.analytics, name='analytics'),
    path('analytics-balance', homeViews.analyticsBalance, name='analyticsBalance'),
    path('analytics-expenses', homeViews.analyticsExpenses,
         name='analyticsExpenses'),
    path('analytics-income', homeViews.analyticsIncome, name='analyticsIncome'),
    path('analytics-income-vs-expenses',
         homeViews.analyticsIncomeVsExpenses, name='analyticsIncomeVsExpenses'),
    path('analytics-transaction-history', homeViews.analyticsTransactionHistory,
         name='analyticsTransactionHistory'),
    path('bank-add-successful', homeViews.bankAddSuccessful,
         name='bankAddSuccessful'),
    path('blank', homeViews.blank, name='blank'),
    path('budgets', homeViews.budgets, name='budgets'),
    path('chart', homeViews.chart, name='chart'),
    path('demo', homeViews.demo, name='demo'),
    path('goals', homeViews.goals, name='goals'),
    path('id-front-and-back-upload', homeViews.idFrontAndBackUpload,
         name='idFrontAndBackUpload'),
    path('index', homeViews.index, name='index'),
    path('locked', homeViews.locked, name='locked'),
    path('notifications', homeViews.notifications, name='notifications'),
    path('otp-code', homeViews.otpCode, name='otpCode'),
    path('otp-phone', homeViews.otpPhone, name='otpPhone'),
    path('page-error', homeViews.pageError, name='pageError'),
    path('privacy', homeViews.privacy, name='privacy'),
    path('profile', homeViews.profile, name='profile'),
    path('reset', homeViews.reset, name='reset'),
    path('settings', homeViews.settings, name='settings'),
    path('settings-api', homeViews.settingsApi, name='settingsApi'),
    path('settings-bank', homeViews.settingsBank, name='settingsBank'),
    path('settings-categories', homeViews.settingsCategories,
         name='settingsCategories'),
    path('settings-currencies', homeViews.settingsCurrencies,
         name='settingsCurrencies'),
    path('settings-general', homeViews.settingsGeneral, name='settingsGeneral'),
    path('settings-profile', homeViews.settingsProfile, name='settingsProfile'),
    path('settings-security', homeViews.settingsSecurity, name='settingsSecurity'),
    path('settings-session', homeViews.settingsSession, name='settingsSession'),
    path('signin', homeViews.signin, name='signin'),
    path('signup', homeViews.signup, name='signup'),
    path('support', homeViews.support, name='support'),
    path('support-create-ticket', homeViews.supportCreateTicket,
         name='supportCreateTicket'),
    path('support-ticket-details', homeViews.supportTicketDetails,
         name='supportTicketDetails'),
    path('support-tickets', homeViews.supportTickets, name='supportTickets'),
    path('verified-id', homeViews.verifiedId, name='verifiedId'),
    path('verify-email', homeViews.verifyEmail, name='verifyEmail'),
    path('verify-id', homeViews.verifyId, name='verifyId'),
    path('verifying-id', homeViews.verifyingId, name='verifyingId'),
    path('wallets', homeViews.wallets, name='wallets'),
    path('wallets/<int:account_id>/', homeViews.wallet_detail, name='wallet_detail'),
    
    # CORRIGIDO: Use 'homeViews' em vez de 'views'
    path('excluir-conta/<int:account_id>/', homeViews.delete_bank_account, name='deleteBankAccount'),
    path('excluir-cartao/<int:card_id>/', homeViews.delete_credit_card, name='deleteCreditCard'),
]