# Generated by Django 5.2.4 on 2025-08-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArvyoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
