# Generated by Django 5.2.4 on 2025-08-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArvyoApp', '0005_goal_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color_class',
            field=models.CharField(default='bg-blue-500', help_text="Classe da cor do ícone, ex: 'bg-blue-500'", max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_class',
            field=models.CharField(default='fi fi-rr-tags', help_text="Classe do ícone, ex: 'fi fi-rr-shopping-cart'", max_length=100),
        ),
    ]
