# Generated by Django 5.2.4 on 2025-08-03 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArvyoApp', '0007_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_number',
            new_name='card_number_masked',
        ),
        migrations.RemoveField(
            model_name='card',
            name='cvc',
        ),
    ]
