# Generated by Django 5.2.4 on 2025-08-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArvyoApp', '0008_rename_card_number_card_card_number_masked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='brand',
            field=models.CharField(default='Não Informado', max_length=50),
            preserve_default=False,
        ),
    ]
