# Generated by Django 5.2.4 on 2025-08-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArvyoApp', '0009_card_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_name',
            field=models.CharField(default='Meu Cartão', max_length=255),
        ),
    ]
